/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'andreina' at '11/26/16 11:37 PM' with Gradle 2.14.1
 *
 * @author andreina, @date 11/26/16 11:37 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
